bundler_args: --without production --jobs=4 --retry=5
language: ruby
sudo: false

rvm:
  - "2.1.1"

addons:
  apt_packages:
    - graphicsmagick

matrix:
  include:
    - { rvm: "2.1.1" }

before_install:
  - "npm -g install jshint"
  - "npm -g install jscs"
  - "gem install scss-lint"
  - "scss-lint ."

before_script:
  - "bin/rake db:create"
  - "bin/rake db:migrate"
